name: Build CI

on: [push, pull_request]

jobs:
  clippy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: 
        rust-toolchain: [nightly, nightly-2024-05-02]
    env:
      RUSTUP_TOOLCHAIN: ${{ matrix.rust-toolchain }}
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ matrix.rust-toolchain }}
        components: rust-src, clippy, rustfmt
        targets: x86_64-unknown-none, riscv64gc-unknown-none-elf, aarch64-unknown-none, aarch64-unknown-none-softfloat
    - name: Check rust version
      run: rustc --version --verbose      
    - name: Clippy for the default target
      run: make clippy
    - name: Clippy for x86_64
      run: make clippy ARCH=x86_64
    - name: Clippy for riscv64
      run: make clippy ARCH=riscv64
    - name: Clippy for aarch64
      run: make clippy ARCH=aarch64
    - name: Check code format
      run: cargo fmt --all -- --check

  build-external:
    uses: Starry-OS/Starry/.github/workflows/build.yml@main
    with:
      # The directory to Top test, which need to be empty or not exist in this repository
      TopTestDirectory: StarryTest
      CallerPackage: linux_syscall_api
      CallerRepository: ${{ github.repository }}
      CallerCommit: ${{ github.sha }}