name: Test CI

on: [push, pull_request]
     
env:
  qemu-version: 8.2.0
  rust-toolchain: nightly-2024-05-02


jobs:
  test-external:
    uses: Starry-OS/Starry/.github/workflows/test.yml@main
    with:
      # The directory to Top test, which need to be empty or not exist in this repository
      TopTestDirectory: StarryTest
      CallerPackage: linux_syscall_api
      CallerRepository: ${{ github.repository }}
      CallerCommit: ${{ github.sha }}
